version: "3.9"
services:
  clothing-model:
    image: clothing-model:xception-v4-001 # tf-serving model image
  gateway:
    image: clothing-model-gateway:002 # flask gateway image (v002)
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - "9696:9696"