apiVersion: v1
kind: Service
metadata: # name of the service ('ping')
  name: ping
spec:
  type: LoadBalancer # type of the service (external in this case)
  selector: # which pods qualify for forwarding requests
    app: ping
  ports:
  - port: 80 # port of the service
    targetPort: 9696 # port of the pod
