apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        # image: clothing-model-gateway:002 # image name when testing locally
        image: 039161193448.dkr.ecr.ap-south-1.amazonaws.com/mlzoomcamp-images:clothing-model-gateway-002
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 9696
        env: # set the enivornment variable for model
          - name: TF_SERVING_HOST
            value: tf-serving-clothing-model.default.svc.cluster.local:8500
